# Generated by Django 5.1 on 2024-08-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0001_initial"),
        ("notes", "0003_rename_note_collaborator_note_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="label",
            field=models.ManyToManyField(related_name="label", to="label.label"),
        ),
    ]
