# Generated by Django 5.1 on 2024-08-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_rename_is_verfied_user_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("url", models.TextField()),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "log",
            },
        ),
    ]
